
import os
from langchain.llms import AI21
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain, SimpleSequentialChain
from secret_key import AI21_API_KEY

os.environ['AI21_API_KEY'] = AI21_API_KEY

llm = AI21(temperature=1)

health_recommendation_prompt = PromptTemplate(
    input_variables=['text'],
    template="{text} Based on your information (age, gender, medical history), I recommend personalized health tips such as diet suggestions, exercise routines, and preventive care measures."
)

medication_reminder_prompt = PromptTemplate(
    input_variables=['text'],
    template="{text} I can help you set medication schedules and send reminders for doses, refills, and potential interactions."
)

chain_health_recommendation = LLMChain(llm=llm, prompt=health_recommendation_prompt, output_key='output_chain')
chain_medication_reminder = LLMChain(llm=llm, prompt=medication_reminder_prompt, output_key='output_chains')

chain = SimpleSequentialChain(chains=[chain_health_recommendation, chain_medication_reminder])

def run_langchain(input_data):
    """
    Runs the LangChain pipeline with input data.

    Args:
    - input_data (str): Input text for the LangChain pipeline.

    Returns:
    - str: Response generated by the LangChain pipeline.
    """
    return chain.run(input_data)


